Luke/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('luke_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

luke_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.DoctorsView_Home.as_view(), name="doctor_list_home"),
    path('doctors/',  views.DoctorsView_List.as_view(), name="doctor_list"),
    path('contacts/',  views.Contact.as_view(), name="contacts"),
    path('service/',  views.Service_List.as_view(), name="service"),
    path('news/',  views.NewsView_List.as_view(), name="news"),
    path("<int:pk>", views.NewsView_Detail.as_view(), name="news_detail"),
]

luke_app/models.py
from django.db import models


class News(models.Model):
    """ Новости """
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    photo_news = models.ImageField(upload_to='photo/', null=True, blank=False)

    def __str__(self):
        return self.title

    def get_short_content(self):
        # Разделите содержимое на отдельные слова
        words = self.content.split()

        # Верните только первые пять слов (или меньше, если содержимое короче)
        return ' '.join(words[:20])

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"


class Service(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    price_discount = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Услуга Общая"
        verbose_name_plural = "Услуги_Общие"


class Service_Massage(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Услуга Массаж"
        verbose_name_plural = "Услуги Массажа"


class Service_Dantist(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    amount = models.DecimalField(max_digits=3, decimal_places=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Стоматологическая услуга"
        verbose_name_plural = "Стоматологические услуги"


class Service_Ultrasound(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    price_discount = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Услуга УЗИ"
        verbose_name_plural = "Услуги УЗИ"


class Doctor(models.Model):
    """Доктора"""
    Second_Name = models.CharField(max_length=50)
    First_Name = models.CharField(max_length=50)
    Sur_Name = models.CharField(max_length=50)
    specialty = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='doctors/', null=True, blank=True)
    bio = models.TextField(blank=False)

    def __str__(self):
        return self.First_Name

    class Meta:
        verbose_name = "Доктор"
        verbose_name_plural = "Доктора"

luke_app/views.py
from django.views.generic import ListView, DetailView
from .models import News, Doctor, Service, Service_Massage, Service_Dantist, Service_Ultrasound


class DoctorsView_Home(ListView):
    model = Doctor
    queryset = Doctor.objects.all()[:4]
    template_name = "luke_app/index.html"
    context_object_name = "doctors"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news'] = News.objects.all()[:3]
        return context


class DoctorsView_List(ListView):
    model = Doctor
    queryset = Doctor.objects.all()
    template_name = "luke_app/doctors.html"
    context_object_name = "doctor_list"


class NewsView_List(ListView):
    model = News
    queryset = News.objects.all()
    template_name = "luke_app/news_list.html"
    context_object_name = "news_list"


class NewsView_Detail(DetailView):
    model = News
    slug_field = "id"
    template_name = "luke_app/news_detail.html"
    context_object_name = "news_det"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['news_list'] = News.objects.all()[:3]
        return context


class NewsView_Detail_List(ListView):
    model = News
    queryset = News.objects.all()[:3]
    template_name = "luke_app/news_detail.html"
    context_object_name = "news_list_detail"


class Service_List(ListView):
    model = Service
    template_name = "luke_app/service.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        context['massages'] = Service_Massage.objects.all()
        context['dantists'] = Service_Dantist.objects.all()
        context['ultrasounds'] = Service_Ultrasound.objects.all()
        return context


class Contact(ListView):
    model = News
    template_name = "luke_app/contact.html"

templates/luke_app/contact.html
 {% extends 'luke_app/index.html' %}
<!DOCTYPE html>
{% load static %}
<html lang="ru">

  <body>
    {% block header %}
    <nav class="navbar py-4 navbar-expand-lg ftco_navbar navbar-light bg-light flex-row">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-3 px-md-0">
    			<div class="col-lg-1 col-5 col-md-2 col-sm-2 pr-4 align-items-center ">
		    		<a class="navbar-brand" href="{% url 'doctor_list_home' %}"><img class="img-fluid" src="{% static 'images/Logo.png' %}"></a>
	    		</div>
	    		<div class="col-lg-10 d-none d-md-block">
		    		<div class="row d-flex">
			    		<div class="col-md-4 pr-4 d-flex topper align-items-center">
			    			<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-map"></span></div>
						    <span class="text">ул.Победы 84,Токмок, Чуйский район, Чуйская область</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">Email: youremail@email.com</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">Телефон: +996 553‒70‒57‒65</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </nav>
	  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Меню
	      </button>
	      <p class="button-custom order-lg-last mb-0"><a href="https://api.whatsapp.com/send/?phone=%2B996553705765&text&type=phone_number&app_absent=0" class="btn btn-secondary py-2 px-3">WhatsApp</a></p>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">

	        	<li class="nav-item "><a href="{% url 'doctor_list_home' %}" class="nav-link pl-0">Главная</a></li>
	        	<li class="nav-item "><a href="{% url 'doctor_list' %}" class="nav-link">Врачи</a></li>
	        	<li class="nav-item"><a href="{% url 'service' %}" class="nav-link">Услуги</a></li>
	        	<li class="nav-item"><a href="{% url 'news' %}" class="nav-link">Новости</a></li>
	          <li class="nav-item active"><a href="{% url 'contacts' %}" class="nav-link">Контакты</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>

    {% endblock header %}
    {% block content %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_1.jpeg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Наши контакты</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'doctor_list_home' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Контакты <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section ftco-no-pt ftco-no-pb contact-section">
			<div class="container">
				<div class="row d-flex align-items-stretch no-gutters">

					<div class="col-md-12 d-flex align-items-stretch">
						<div id="map">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1263.8655079589719!2d75.29282180171877!3d42.847531709351514!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x389c0a7d4eb4df17%3A0x85ef7dbc28fbe591!2shope%20clinic!5e0!3m2!1sen!2skg!4v1684496982883!5m2!1sen!2skg" width="100%" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
					</div>
				</div>
			</div>
		</section>
		
		<section class="ftco-section contact-section">
      <div class="container">
        <div class="row d-flex mb-5 contact-info">
          <div class="col-md-12 mb-4">
            <h2 class="h4">Контакная информация</h2>
          </div>
          <div class="w-100"></div>
          <div class="col-md-3 d-flex">
          	<div class="bg-light d-flex align-self-stretch box p-4">
	            <p><span>Адрес:</span>ул.Победы 84,Токмок, Чуйский район, Чуйская область</p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="bg-light d-flex align-self-stretch box p-4">
	            <p><span>Phone:</span> <a href="tel:+996 553‒70‒57‒65">+996 553‒70‒57‒65</a></p>
	          </div>
          </div>
          <div class="col-md-3 d-flex">
          	<div class="bg-light d-flex align-self-stretch box p-4">
	            <p><span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
	          </div>
          </div>
        </div>
      </div>
    </section>
{% endblock content %}

  </body>
</html>

templates/luke_app/doctors.html
{% extends 'luke_app/index.html' %}
<!DOCTYPE html>
{% load static %}

<html lang="ru">

  <body>
    {% block header %}

        <nav class="navbar py-4 navbar-expand-lg ftco_navbar navbar-light bg-light flex-row">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-3 px-md-0">
    			<div class="col-lg-1 col-5 col-md-2 col-sm-2 pr-4 align-items-center ">
		    		<a class="navbar-brand" href="{% url 'doctor_list_home' %}"><img class="img-fluid" src="{% static 'images/Logo.png' %}"></a>
	    		</div>
	    		<div class="col-lg-10 d-none d-md-block">
		    		<div class="row d-flex">
			    		<div class="col-md-4 pr-4 d-flex topper align-items-center">
			    			<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-map"></span></div>
						    <span class="text">ул.Победы 84,Токмок, Чуйский район, Чуйская область</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">Email: youremail@email.com</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">Телефон: +996 553‒70‒57‒65</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </nav>
	  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Меню
	      </button>
	      <p class="button-custom order-lg-last mb-0"><a href="https://api.whatsapp.com/send/?phone=%2B996553705765&text&type=phone_number&app_absent=0" class="btn btn-secondary py-2 px-3">WhatsApp</a></p>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">
	        	<li class="nav-item "><a href="{% url 'doctor_list_home' %}" class="nav-link pl-0">Главная</a></li>
	        	<li class="nav-item active"><a href="{% url 'doctor_list' %}" class="nav-link">Врачи</a></li>
	        	<li class="nav-item"><a href="{% url 'service' %}" class="nav-link">Услуги</a></li>
	        	<li class="nav-item"><a href="{% url 'news' %}" class="nav-link">Новости</a></li>
	          <li class="nav-item"><a href="{% url 'contacts' %}" class="nav-link">Контакты</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>

    {% endblock header %}

{% block content %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_2.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Квалифицированные врачи</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'doctor_list_home' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span>Врачи <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section">
			<div class="container">
				<div class="row">
                    {% for doctor in doctor_list %}
                    <div class="col-md-6 col-lg-3 ftco-animate">
						<div class="staff">
							<div class="img-wrap d-flex align-items-stretch">
								<div class="img align-self-stretch" style="background-image: url({{ doctor.photo.url }});"></div>
							</div>
							<div class="text pt-3 text-center">
								<h3>{{ doctor.Second_Name }}  {{ doctor.First_Name }}</h3>
								<span class="position mb-2">{{ doctor.specialty }}</span>
								<div class="faded">
									<p>{{ doctor.bio }}</p>
									<ul class="ftco-social text-center">
		                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
		                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
		                <li class="ftco-animate"><a href="#"><span class="icon-google-plus"></span></a></li>
		                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
		              </ul>
	              </div>
							</div>
						</div>
					</div>


            {% endfor %}
				</div>

			</div>
		</section>
    {% endblock content %}
  </body>
</html>

templates/luke_app/news_detail.html
{% extends 'luke_app/index.html' %}
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <body>
    {% block header %}
    <nav class="navbar py-4 navbar-expand-lg ftco_navbar navbar-light bg-light flex-row">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-3 px-md-0">
    			<div class="col-lg-1 col-5 col-md-2 col-sm-2 pr-4 align-items-center ">
		    		<a class="navbar-brand" href="{% url 'doctor_list_home' %}"><img class="img-fluid" src="{% static 'images/Logo.png' %}"></a>
	    		</div>
	    		<div class="col-lg-10 d-none d-md-block">
		    		<div class="row d-flex">
			    		<div class="col-md-4 pr-4 d-flex topper align-items-center">
			    			<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-map"></span></div>
						    <span class="text">ул.Победы 84,Токмок, Чуйский район, Чуйская область</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">Email: youremail@email.com</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">Телефон: +996 553‒70‒57‒65</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </nav>
	  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Меню
	      </button>
	      <p class="button-custom order-lg-last mb-0"><a href="https://api.whatsapp.com/send/?phone=%2B996553705765&text&type=phone_number&app_absent=0" class="btn btn-secondary py-2 px-3">WhatsApp</a></p>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">

	        	<li class="nav-item "><a href="{% url 'doctor_list_home' %}" class="nav-link pl-0">Главная</a></li>
	        	<li class="nav-item"><a href="{% url 'doctor_list' %}" class="nav-link">Врачи</a></li>
	        	<li class="nav-item"><a href="{% url 'service' %}" class="nav-link">Услуги</a></li>
	        	<li class="nav-item active"><a href="{% url 'news' %}" class="nav-link">Новости</a></li>
	          <li class="nav-item"><a href="{% url 'contacts' %}" class="nav-link">Контакты</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>

    {% endblock header %}
    {% block content %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_3.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">{{ news_det.title }}</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="index.html">Новости <i class="ion-ios-arrow-forward"></i></a></span> <span>Новость <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section">
			<div class="container">
				<div class="row">
          <div class="col-lg-8 ftco-animate">
              <img  src="{{ news_det.photo_news.url }}" alt="hope" class="img-fluid">
            <p>{{ news_det.content }}</p>

          </div>

          <div class="col-lg-4 sidebar ftco-animate">
            <div class="sidebar-box ftco-animate">
              <h3>Другие новости</h3>
                {% for news in news_list %}
              <div class="block-21 mb-4 d-flex">
                <div class="text">
                  <h3 class="heading"><a href="{% url 'news_detail' news.id %}">{{ news.title }}</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> {{ news.date_created }}</a></div>
                  </div>
                </div>
              </div>
                {% endfor %}
            </div>
          </div><!-- END COL -->
        </div>
			</div>
		</section>
{% endblock content %}

    
  </body>
</html>

templates/luke_app/service.html
{% extends 'luke_app/index.html' %}
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <body>
     {% block header %}
    <nav class="navbar py-4 navbar-expand-lg ftco_navbar navbar-light bg-light flex-row">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-3 px-md-0">
    			<div class="col-lg-1 col-5 col-md-2 col-sm-2 pr-4 align-items-center ">
		    		<a class="navbar-brand" href="{% url 'doctor_list_home' %}"><img class="img-fluid" src="{% static 'images/Logo.png' %}"></a>
	    		</div>
	    		<div class="col-lg-10 d-none d-md-block">
		    		<div class="row d-flex">
			    		<div class="col-md-4 pr-4 d-flex topper align-items-center">
			    			<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-map"></span></div>
						    <span class="text">ул.Победы 84,Токмок, Чуйский район, Чуйская область</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">Email: youremail@email.com</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon bg-white mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">Телефон: +996 553‒70‒57‒65</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </nav>
	  <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Меню
	      </button>
	      <p class="button-custom order-lg-last mb-0"><a href="https://api.whatsapp.com/send/?phone=%2B996553705765&text&type=phone_number&app_absent=0" class="btn btn-secondary py-2 px-3">WhatsApp</a></p>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav mr-auto">

	        	<li class="nav-item "><a href="{% url 'doctor_list_home' %}" class="nav-link pl-0">Главная</a></li>
	        	<li class="nav-item"><a href="{% url 'doctor_list' %}" class="nav-link">Врачи</a></li>
	        	<li class="nav-item active"><a href="{% url 'service' %}" class="nav-link">Услуги</a></li>
	        	<li class="nav-item"><a href="{% url 'news' %}" class="nav-link">Новости</a></li>
	          <li class="nav-item"><a href="{% url 'contacts' %}" class="nav-link">Контакты</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>

    {% endblock header %}
     {% block content %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_2.jpg' %});" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Услуги</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'doctor_list_home' %}">Главная <i class="ion-ios-arrow-forward"></i></a></span> <span> Услуги <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>
		
		<section class="ftco-section ftco-departments bg-light">
    	<div class="container">
    		<div class="row justify-content-center my-1 pb-2">
          <div class="col-md-8 text-center heading-section ftco-animate">
  <section class="ftco-section ftco-departments bg-light">
    	<div class="container">
    		<div class="row justify-content-center my-1 pb-2">
          <div class="col-md-8 text-center heading-section ftco-animate">

            <h2 class="mb-4">Прайс-лист  Общих услуг</h2>
          </div>
        </div>
    		<div class="row">
        	<div class="col-12 ftco-animate">
        		<div class="pricing-entry  text-center">
                    <table>
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Название</th>
                            <th>Цена</th>
                             <th>Цена со скидкой</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for service in service_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ service.name }}</td>
                                <td>{{ service.price }} сом </td>
                             <td>{{ service.price_discount }} сом </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
        		</div>
        	</div>
        </div>
    	</div>
    </section>

            <h2 class="mb-4">Прайс-лист на услуги массажа</h2>
          </div>
        </div>
    		<div class="row">
        	<div class="col-12 ftco-animate">
        		<div class="pricing-entry  text-center">
                    <table>
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Название</th>
                            <th>Цена</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for service in massages %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ service.name }}</td>
                                <td>{{ service.price }} сом</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
        		</div>
        	</div>
        </div>
    	</div>
    </section>



         <section class="ftco-section ftco-departments bg-light">
    	<div class="container">
    		<div class="row justify-content-center my-1 pb-2">
          <div class="col-md-8 text-center heading-section ftco-animate">

            <h2 class="mb-4">Прайс-лист на услуги УЗИ</h2>
          </div>
        </div>
    		<div class="row">
        	<div class="col-12 ftco-animate">
        		<div class="pricing-entry  text-center">
                    <table>
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Название</th>
                            <th>Цена</th>
                             <th>Цена со скидкой</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for service in ultrasounds %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ service.name }}</td>
                                <td>{{ service.price }} сом </td>
                             <td>{{ service.price_discount }} сом</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
        		</div>
        	</div>
        </div>
    	</div>
    </section>


           <section class="ftco-section ftco-departments bg-light">
    	<div class="container">
    		<div class="row justify-content-center my-1 pb-2">
          <div class="col-md-8 text-center heading-section ftco-animate">

            <h2 class="mb-4">Прайс-лист на услуги Стоматологии</h2>
          </div>
        </div>
    		<div class="row">
        	<div class="col-12 ftco-animate">
        		<div class="pricing-entry  text-center">
                    <table>
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Название</th>
                            <th>Цена</th>
                             <th>За 1 зуб</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for service in dantists %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ service.name }}</td>
                                <td>{{ service.price }} сом </td>
                             <td>{{ service.amount }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
        		</div>
        	</div>
        </div>
    	</div>
    </section>




 {% endblock content %}
    
  </body>
</html>